title: My Amazing Site
author: My Name
email: my-email@domain.com
description: >
  This is my amazing site!
copyright: My Name

# EnchantedCode Theme Configs
enable_breadcrumb: true

plugins:
 - jekyll-feed
 - jekyll-seo-tag
